# Generated by Django 5.2.5 on 2025-08-29 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_remove_patient_firebase_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=100)),
                ('oss_path', models.CharField(max_length=500)),
                ('raw_content', models.TextField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('analysis_summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('openai_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost_estimate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_analyses', to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_analyses', to='core.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('primary_diagnosis', models.TextField()),
                ('secondary_diagnoses', models.TextField(blank=True)),
                ('procedures_performed', models.TextField(blank=True)),
                ('medications', models.TextField()),
                ('vital_signs', models.TextField(blank=True)),
                ('lab_results', models.TextField(blank=True)),
                ('imaging_results', models.TextField(blank=True)),
                ('hospital_course', models.TextField()),
                ('discharge_condition', models.CharField(max_length=100)),
                ('discharge_instructions', models.TextField()),
                ('follow_up_plan', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('openai_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost_estimate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summaries', to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summaries', to='core.patient')),
                ('generated_from_analyses', models.ManyToManyField(related_name='discharge_summaries', to='openai_integration.documentanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
