# Generated by Django 5.2.5 on 2025-08-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargesummary',
            name='formatted_summary',
            field=models.TextField(blank=True),
        ),
    ]
