# Generated by Django 5.2.5 on 2025-08-28 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('admission_date', models.DateField()),
                ('room_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending Discharge', 'Pending Discharge'), ('Discharged', 'Discharged')], default='Active', max_length=32)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='core.doctor')),
            ],
            options={
                'indexes': [models.Index(fields=['doctor'], name='core_patien_doctor__c2395f_idx'), models.Index(fields=['last_name', 'first_name'], name='core_patien_last_na_5d3812_idx')],
            },
        ),
    ]
