# Generated by Django 5.2.5 on 2025-08-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='institution',
            field=models.CharField(blank=True, help_text='Medical institution where the doctor works', max_length=255, null=True),
        ),
    ]
