# Generated by Django 5.2.5 on 2025-08-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctor_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='room_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='occupant_type',
            field=models.CharField(default='Room', help_text='Type of occupant (Room, Bed, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupant_value',
            field=models.CharField(blank=True, help_text='Value of occupant (Room number, Bed number, etc.)', max_length=50),
        ),
    ]
