# Generated by Django 5.2.5 on 2025-08-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_patient_room_number_patient_occupant_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='firebase_uid',
            field=models.CharField(blank=True, help_text='Firebase UUID for the patient', max_length=128, null=True, unique=True),
        ),
    ]
