# Generated by Django 5.2.5 on 2025-08-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patient_firebase_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='firebase_uid',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_firebase_uid',
            field=models.CharField(blank=True, help_text='Firebase UID of the doctor who owns this patient', max_length=128, null=True),
        ),
    ]
