# Generated by Django 5.2.5 on 2025-08-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_patient_firebase_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='occupant_type',
            field=models.CharField(choices=[('Room', 'Room'), ('Bed', 'Bed'), ('ER Patient', 'ER Patient')], default='Room', help_text='Type of accommodation for the patient', max_length=32),
        ),
        migrations.AlterField(
            model_name='patient',
            name='occupant_value',
            field=models.CharField(blank=True, help_text='Room number, bed number, or ER designation', max_length=100),
        ),
    ]
